"""Initial schema with all tables

Revision ID: 5d81289aef04
Revises: 
Create Date: 2025-09-09 20:37:44.271257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d81289aef04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_posts', sa.Integer(), nullable=True),
    sa.Column('total_comments', sa.Integer(), nullable=True),
    sa.Column('api_calls', sa.Integer(), nullable=True),
    sa.Column('api_cost_estimate', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term')
    )
    op.create_table('subreddits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('daily_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=True),
    sa.Column('subreddit_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_posts', sa.Integer(), nullable=True),
    sa.Column('total_comments', sa.Integer(), nullable=True),
    sa.Column('avg_post_sentiment', sa.Float(), nullable=True),
    sa.Column('avg_comment_sentiment', sa.Float(), nullable=True),
    sa.Column('positive_posts', sa.Integer(), nullable=True),
    sa.Column('negative_posts', sa.Integer(), nullable=True),
    sa.Column('neutral_posts', sa.Integer(), nullable=True),
    sa.Column('top_positive_post_id', sa.String(), nullable=True),
    sa.Column('top_negative_post_id', sa.String(), nullable=True),
    sa.Column('most_discussed_post_id', sa.String(), nullable=True),
    sa.Column('keyword_mentions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'subreddit_id', name='unique_daily_summary')
    )
    op.create_index('idx_summary_date', 'daily_summaries', ['date'], unique=False)
    op.create_index('idx_summary_subreddit', 'daily_summaries', ['subreddit_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subreddit_id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('selftext', sa.Text(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_utc', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('num_comments', sa.Integer(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_explanation', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_posts_analysis_run', 'posts', ['analysis_run_id'], unique=False)
    op.create_index('idx_posts_created', 'posts', ['created_utc'], unique=False)
    op.create_index('idx_posts_sentiment', 'posts', ['sentiment_score'], unique=False)
    op.create_index('idx_posts_subreddit', 'posts', ['subreddit_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.Integer(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comments_created', 'comments', ['created_utc'], unique=False)
    op.create_index('idx_comments_post', 'comments', ['post_id'], unique=False)
    op.create_index('idx_comments_sentiment', 'comments', ['sentiment_score'], unique=False)
    op.create_table('post_keywords',
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'keyword_id')
    )
    op.create_table('comment_keywords',
    sa.Column('comment_id', sa.String(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('comment_id', 'keyword_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_keywords')
    op.drop_table('post_keywords')
    op.drop_index('idx_comments_sentiment', table_name='comments')
    op.drop_index('idx_comments_post', table_name='comments')
    op.drop_index('idx_comments_created', table_name='comments')
    op.drop_table('comments')
    op.drop_index('idx_posts_subreddit', table_name='posts')
    op.drop_index('idx_posts_sentiment', table_name='posts')
    op.drop_index('idx_posts_created', table_name='posts')
    op.drop_index('idx_posts_analysis_run', table_name='posts')
    op.drop_table('posts')
    op.drop_index('idx_summary_subreddit', table_name='daily_summaries')
    op.drop_index('idx_summary_date', table_name='daily_summaries')
    op.drop_table('daily_summaries')
    op.drop_table('subreddits')
    op.drop_table('keywords')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
