keywords:
  products:
    - Claude
    - Claude 3
    - Claude 3.5
    - Opus
    - Opus 4.1
    - Sonnet
    - Sonnet 4
    - Haiku
  features:
    - Artifacts
    - Projects
    - Claude Code
    - Computer Use
    - Vision
  company:
    - Anthropic
    - Constitutional AI
    - RLHF
  competitors:
    - ChatGPT
    - GPT-4
    - GPT4
    - Gemini
    - Copilot
    - Codex

